import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  ArrowLeft,
  Clock,
  ExternalLink,
  ShieldCheck,
  Globe,
  Bookmark,
  HelpCircle,
  TrendingUp,
  Share2,
  Download,
  Check,
  Newspaper,
} from 'lucide-react';
import apiClient from '../lib/apiClient.js';
import SeverityBadge from '../components/common/SeverityBadge.jsx';
import CredibilityBadge from '../components/common/CredibilityBadge.jsx';
import DirectionBadge from '../components/common/DirectionBadge.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { translateNewsText, translateNewsArray } from '../i18n/newsContentTranslations.js';
import { getNewsEditorialImage } from '../lib/newsImages.js';

// ─── Standalone Event Article & Dossier Page ───────────────────────────────────
// Full-width editorial article page matching modern newspaper standards.
// ─────────────────────────────────────────────────────────────────────────────

export default function EventDetails() {
  const { t, i18n } = useTranslation();
  const { id } = useParams();
  const navigate = useNavigate();
  const { isAuthenticated, isBookmarked, toggleBookmark } = useAuth();

  const [eventData, setEventData] = useState(null);
  const [impacts, setImpacts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  const lang = i18n.language || 'en';

  useEffect(() => {
    let isMounted = true;

    async function loadData() {
      try {
        setIsLoading(true);
        setError(null);

        const [eventRes, impactsRes] = await Promise.all([
          apiClient.get(`/events/${id}`),
          apiClient.get(`/events/${id}/impacts`),
        ]);

        if (isMounted) {
          setEventData(eventRes.data);
          setImpacts(impactsRes.data || []);
        }
      } catch (err) {
        if (isMounted) setError(err.message || t('errors.generic'));
      } finally {
        if (isMounted) setIsLoading(false);
      }
    }

    if (id) loadData();

    return () => {
      isMounted = false;
    };
  }, [id, t]);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportBriefing = () => {
    if (!eventData) return;

    const briefing = `
================================================================================
GEOPOLITICAL INTELLIGENCE DOSSIER: ${eventData.eventType?.replace(/_/g, ' ')}
Generated by GeoMonitor AI Intelligence Engine
Date: ${new Date(eventData.createdAt).toUTCString()}
================================================================================

SUMMARY:
${eventData.summary}

SEVERITY: ${eventData.severity}
CREDIBILITY: ${eventData.credibilityLabel} (${eventData.credibilityScore})
AFFECTED COUNTRIES: ${(eventData.countries || []).join(', ') || 'N/A'}
AFFECTED SECTORS: ${(eventData.sectors || []).join(', ') || 'N/A'}
KEY ENTITIES: ${(eventData.entities || []).join(', ') || 'N/A'}

--------------------------------------------------------------------------------
CONFIRMED FACTS & CLAIMS:
${(eventData.facts || []).map((f) => `• ${f}`).join('\n') || 'None recorded'}

REPORTED UNCERTAINTIES:
${(eventData.uncertainties || []).map((u) => `? ${u}`).join('\n') || 'None recorded'}

--------------------------------------------------------------------------------
DOMAIN IMPACT EVALUATIONS:
${impacts
  .map(
    (imp) => `
[${imp.domain}] Direction: ${imp.direction} | Severity: ${imp.severity} | Confidence: ${Math.round(imp.confidenceScore * 100)}%
Explanation: ${imp.explanation}
`
  )
  .join('')}
================================================================================
`;

    const blob = new Blob([briefing], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `GeoMonitor-Dossier-${eventData._id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="py-24 flex flex-col items-center justify-center text-slate-400 space-y-3">
        <div className="w-8 h-8 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin" />
        <p className="text-xs text-slate-500">{t('eventDetail.loading', { defaultValue: 'Loading article dossier...' })}</p>
      </div>
    );
  }

  if (error || !eventData) {
    return (
      <div className="p-10 rounded-2xl border border-rose-200 bg-rose-50 text-center text-rose-700 space-y-4 max-w-xl mx-auto">
        <p className="text-sm">{error || t('errors.notFoundDesc')}</p>
        <button
          onClick={() => navigate('/')}
          className="px-5 py-2.5 rounded-full bg-slate-900 text-white font-bold text-xs hover:bg-slate-800 transition"
        >
          {t('errors.returnHome', { defaultValue: 'Return to News Feed' })}
        </button>
      </div>
    );
  }

  const localizedSummary = translateNewsText(eventData.summary, lang);
  const primaryArticle = eventData.primaryArticleId;
  const localizedArticleExcerpt = primaryArticle?.excerpt
    ? translateNewsText(primaryArticle.excerpt, lang)
    : null;

  const eventTypeLabel = eventData.eventType
    ? t(`eventTypes.${eventData.eventType}`, { defaultValue: eventData.eventType.replace(/_/g, ' ') })
    : 'EVENT DOSSIER';

  const bookmarked = isBookmarked ? isBookmarked(eventData._id) : false;
  const imageUrl = getNewsEditorialImage(eventData);
  const sourceName = primaryArticle?.sourceId?.name || 'World News Wire';

  const formattedDate = eventData.createdAt
    ? new Date(eventData.createdAt).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      })
    : '';

  return (
    <article className="space-y-8 max-w-4xl mx-auto w-full">
      {/* Top Breadcrumb & Action Toolbar */}
      <div className="flex items-center justify-between gap-4 flex-wrap pb-4 border-b border-slate-200">
        <button
          onClick={() => navigate(-1)}
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-slate-950 transition cursor-pointer"
        >
          <ArrowLeft size={15} />
          <span>{t('feed.allStories', { defaultValue: 'Back to Stories' })}</span>
        </button>

        <div className="flex items-center gap-2">
          {/* Export text briefing */}
          <button
            onClick={handleExportBriefing}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-slate-200 bg-white text-slate-700 hover:bg-slate-100 text-xs font-semibold transition cursor-pointer shadow-2xs"
          >
            <Download size={12} />
            <span className="hidden sm:inline">Export Briefing</span>
          </button>

          {/* Share */}
          <button
            onClick={handleCopyLink}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-slate-200 bg-white text-slate-700 hover:bg-slate-100 text-xs font-semibold transition cursor-pointer shadow-2xs"
          >
            {copied ? <Check size={13} className="text-emerald-600" /> : <Share2 size={12} />}
            <span>{copied ? 'Copied' : 'Share'}</span>
          </button>

          {/* Bookmark */}
          {isAuthenticated && (
            <button
              onClick={() => toggleBookmark(eventData._id)}
              className={`inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-xs font-semibold transition cursor-pointer shadow-2xs ${
                bookmarked
                  ? 'bg-slate-900 text-white'
                  : 'bg-white border border-slate-200 text-slate-700 hover:bg-slate-100'
              }`}
            >
              <Bookmark size={12} fill={bookmarked ? 'currentColor' : 'none'} />
              <span>{bookmarked ? 'Saved' : 'Save'}</span>
            </button>
          )}
        </div>
      </div>

      {/* Main Headline & Metadata */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs font-mono font-bold uppercase tracking-wider text-indigo-700 bg-indigo-50 border border-indigo-200 px-2.5 py-0.5 rounded-full">
            {eventTypeLabel}
          </span>
          <SeverityBadge severity={eventData.severity} size="sm" />
          <CredibilityBadge
            label={eventData.credibilityLabel}
            score={eventData.credibilityScore}
          />
        </div>

        <h1 className="text-2xl sm:text-4xl font-black text-slate-950 leading-[1.18] tracking-tight">
          {localizedSummary}
        </h1>

        <div className="flex items-center gap-3 text-xs text-slate-500 font-mono pt-2 border-t border-slate-100 flex-wrap">
          <span className="flex items-center gap-1.5">
            <Globe size={13} className="text-indigo-600" />
            <span>Source: <strong className="text-slate-800">{sourceName}</strong></span>
          </span>
          <span>•</span>
          <span className="flex items-center gap-1.5">
            <Clock size={13} />
            <span>{formattedDate}</span>
          </span>
        </div>
      </div>

      {/* Editorial Hero Photography Frame */}
      <div className="relative h-72 sm:h-96 w-full rounded-2xl overflow-hidden bg-slate-900 border border-slate-200 shadow-xs">
        <img
          src={imageUrl}
          alt={eventData.summary}
          className="w-full h-full object-cover"
        />
      </div>

      {/* Dedicated Article Summary Card */}
      <div className="p-5 sm:p-6 rounded-2xl border border-indigo-100 bg-indigo-50/50 space-y-3">
        <div className="flex items-center justify-between gap-2 flex-wrap pb-2 border-b border-indigo-100">
          <div className="flex items-center gap-2">
            <Newspaper size={16} className="text-indigo-600" />
            <h2 className="text-xs font-bold font-mono tracking-wide text-slate-900 uppercase">
              {t('eventDetail.articleSummary', { defaultValue: 'Article Summary' })}
            </h2>
          </div>

          {primaryArticle?.url && (
            <a
              href={primaryArticle.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs font-bold text-indigo-700 hover:text-indigo-900 hover:underline inline-flex items-center gap-1 transition-colors"
            >
              <span>{t('eventDetail.readOriginal', { defaultValue: 'Read Original Wire Article' })}</span>
              <ExternalLink size={12} />
            </a>
          )}
        </div>

        {localizedArticleExcerpt ? (
          <p className="text-sm sm:text-base text-slate-700 leading-relaxed">
            {localizedArticleExcerpt}
          </p>
        ) : (
          <div className="text-xs text-slate-500 italic">
            {primaryArticle?.url ? (
              <a
                href={primaryArticle.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-indigo-700 hover:underline inline-flex items-center gap-1 font-medium not-italic"
              >
                {t('eventDetail.summaryUnavailable', { defaultValue: 'Summary unavailable. Read original article →' })}
              </a>
            ) : (
              <span>{t('eventDetail.summaryUnavailable', { defaultValue: 'Summary unavailable.' })}</span>
            )}
          </div>
        )}
      </div>

      {/* Verified Claims vs Reported Uncertainties */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Verified Claims */}
        <div className="p-5 sm:p-6 rounded-2xl border border-slate-200 bg-white space-y-3">
          <div className="flex items-center gap-2 text-xs font-mono font-bold uppercase text-emerald-700">
            <ShieldCheck size={16} className="text-emerald-600" />
            <span>{t('eventDetail.verifiedFacts', { defaultValue: 'Verified Claims & Facts' })}</span>
          </div>
          {eventData.facts && eventData.facts.length > 0 ? (
            <ul className="space-y-2.5 text-xs sm:text-sm text-slate-700">
              {translateNewsArray(eventData.facts, lang).map((fact, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-emerald-600 font-bold mt-0.5">•</span>
                  <span className="leading-relaxed">{fact}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-slate-400 italic">{t('eventDetail.noFacts', { defaultValue: 'No specific claims recorded.' })}</p>
          )}
        </div>

        {/* Reported Uncertainties */}
        <div className="p-5 sm:p-6 rounded-2xl border border-slate-200 bg-white space-y-3">
          <div className="flex items-center gap-2 text-xs font-mono font-bold uppercase text-amber-700">
            <HelpCircle size={16} className="text-amber-600" />
            <span>{t('eventDetail.reportedUncertainties', { defaultValue: 'Reported Uncertainties' })}</span>
          </div>
          {eventData.uncertainties && eventData.uncertainties.length > 0 ? (
            <ul className="space-y-2.5 text-xs sm:text-sm text-slate-700">
              {translateNewsArray(eventData.uncertainties, lang).map((unc, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-amber-600 font-bold mt-0.5">•</span>
                  <span className="leading-relaxed">{unc}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-slate-400 italic">{t('eventDetail.noUncertainties', { defaultValue: 'No uncertainties recorded.' })}</p>
          )}
        </div>
      </div>

      {/* Entities & Geography */}
      <div className="p-6 rounded-2xl border border-slate-200 bg-white space-y-4">
        <h2 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-400">
          KEY GEOGRAPHY & SECTORS
        </h2>

        <div className="flex items-center gap-2 flex-wrap">
          {eventData.countries?.map((country) => (
            <span
              key={country}
              className="px-3 py-1 rounded-md bg-slate-100 border border-slate-200 text-slate-800 text-xs font-medium flex items-center gap-1.5"
            >
              <Globe size={12} className="text-indigo-600" />
              {country}
            </span>
          ))}

          {eventData.sectors?.map((sector) => (
            <span
              key={sector}
              className="px-3 py-1 rounded-md bg-slate-100 border border-slate-200 text-slate-700 text-xs font-mono"
            >
              #{sector}
            </span>
          ))}

          {eventData.entities?.map((ent) => (
            <span
              key={ent}
              className="px-3 py-1 rounded-md bg-slate-50 border border-slate-200 text-slate-600 text-xs"
            >
              {ent}
            </span>
          ))}
        </div>
      </div>

      {/* Domain Impact Evaluations */}
      <div className="space-y-4">
        <h2 className="text-lg font-black text-slate-950 flex items-center gap-2">
          <TrendingUp size={20} className="text-indigo-600" />
          <span>{t('eventDetail.domainImpacts', { defaultValue: 'Domain Impact Assessments' })}</span>
        </h2>

        {impacts.length === 0 ? (
          <div className="p-6 rounded-2xl border border-slate-200 bg-white text-center text-xs text-slate-400">
            {t('eventDetail.noImpacts', { defaultValue: 'No domain impacts assessed for this event yet.' })}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {impacts.map((imp) => {
              const domainLabel = t(`domains.${imp.domain}`, { defaultValue: imp.domain });
              const explanationText = imp.explanation || imp.ruleExplanation || '';
              const localizedImpExplanation = translateNewsText(explanationText, lang);
              return (
                <div
                  key={imp._id}
                  className="p-5 rounded-2xl border border-slate-200 bg-white space-y-3 shadow-2xs"
                >
                  <div className="flex items-center justify-between gap-2 pb-2 border-b border-slate-100">
                    <span className="text-xs font-mono font-bold text-indigo-700 bg-indigo-50 px-2.5 py-0.5 rounded-md border border-indigo-100">
                      {domainLabel}
                    </span>
                    <DirectionBadge direction={imp.direction} size="sm" />
                  </div>

                  <div className="space-y-1 text-xs text-slate-500 font-mono">
                    <div className="flex items-center justify-between">
                      <span>Severity:</span>
                      <span className="font-bold text-slate-900">{imp.severity}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span>Confidence:</span>
                      <span className="font-bold text-indigo-600">
                        {Math.round((imp.confidenceScore || 0.88) * 100)}%
                      </span>
                    </div>
                  </div>

                  {localizedImpExplanation && (
                    <p className="text-xs sm:text-sm text-slate-700 leading-relaxed border-t border-slate-100 pt-2.5">
                      {localizedImpExplanation}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Wire Source Action */}
      {primaryArticle?.url && (
        <div className="p-5 rounded-2xl border border-slate-200 bg-slate-50 flex items-center justify-between flex-wrap gap-4 text-xs">
          <span className="text-slate-600 font-mono">
            Original Source: <strong className="text-slate-900">{sourceName}</strong>
          </span>
          <a
            href={primaryArticle.url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full bg-slate-900 text-white font-bold text-xs hover:bg-slate-800 transition"
          >
            <span>{t('eventDetail.readOriginal', { defaultValue: 'Read Full Wire Article' })}</span>
            <ExternalLink size={13} />
          </a>
        </div>
      )}
    </article>
  );
}
