import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  ArrowLeft,
  Clock,
  ExternalLink,
  ShieldCheck,
  Globe,
  MapPin,
  Bookmark,
  CheckCircle2,
  HelpCircle,
  TrendingUp,
  Share2,
  Download,
  Check,
  Newspaper,
} from 'lucide-react';
import apiClient from '../lib/apiClient.js';
import SeverityBadge from '../components/common/SeverityBadge.jsx';
import CredibilityBadge from '../components/common/CredibilityBadge.jsx';
import DirectionBadge from '../components/common/DirectionBadge.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { translateNewsText, translateNewsArray } from '../i18n/newsContentTranslations.js';

// ─── Event Details Page ───────────────────────────────────────────────────────
// Standalone page for inspecting full intelligence dossier on a specific event.
// ─────────────────────────────────────────────────────────────────────────────

export default function EventDetails() {
  const { t, i18n } = useTranslation();
  const { id } = useParams();
  const navigate = useNavigate();
  const { isAuthenticated, isBookmarked, toggleBookmark } = useAuth();

  const [eventData, setEventData] = useState(null);
  const [impacts, setImpacts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let isMounted = true;

    async function loadData() {
      try {
        setIsLoading(true);
        setError(null);

        const [eventRes, impactsRes] = await Promise.all([
          apiClient.get(`/events/${id}`),
          apiClient.get(`/events/${id}/impacts`),
        ]);

        if (isMounted) {
          setEventData(eventRes.data);
          setImpacts(impactsRes.data || []);
        }
      } catch (err) {
        if (isMounted) setError(err.message || t('errors.generic'));
      } finally {
        if (isMounted) setIsLoading(false);
      }
    }

    if (id) loadData();

    return () => {
      isMounted = false;
    };
  }, [id, t]);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportBriefing = () => {
    if (!eventData) return;

    const briefing = `
================================================================================
GEOPOLITICAL INTELLIGENCE DOSSIER: ${eventData.eventType?.replace(/_/g, ' ')}
Generated by GeoMonitor AI Intelligence Engine
Date: ${new Date(eventData.createdAt).toUTCString()}
================================================================================

SUMMARY:
${eventData.summary}

SEVERITY: ${eventData.severity}
CREDIBILITY: ${eventData.credibilityLabel} (${eventData.credibilityScore})
AFFECTED COUNTRIES: ${(eventData.countries || []).join(', ') || 'N/A'}
AFFECTED SECTORS: ${(eventData.sectors || []).join(', ') || 'N/A'}
KEY ENTITIES: ${(eventData.entities || []).join(', ') || 'N/A'}

--------------------------------------------------------------------------------
CONFIRMED FACTS & CLAIMS:
${(eventData.facts || []).map((f, i) => `[${i + 1}] ${f}`).join('\n')}

REPORTED UNCERTAINTIES:
${(eventData.uncertainties || []).map((u, i) => `[${i + 1}] ${u}`).join('\n') || 'None recorded'}

--------------------------------------------------------------------------------
DOMAIN IMPACT EVALUATION:
${impacts
  .map(
    (imp) =>
      `• Domain: ${imp.domain} | Direction: ${imp.direction} | Severity: ${imp.severity} | Confidence: ${Math.round(imp.confidenceScore * 100)}%\n  Explanation: ${imp.ruleExplanation}`
  )
  .join('\n\n')}

--------------------------------------------------------------------------------
PRIMARY REPORT:
Title: ${eventData.primaryArticleId?.title || 'N/A'}
Source: ${eventData.primaryArticleId?.sourceId?.name || 'News Source'}
URL: ${eventData.primaryArticleId?.url || 'N/A'}
================================================================================
`.trim();

    const blob = new Blob([briefing], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `GeoMonitor-Dossier-${eventData._id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="py-24 text-center text-slate-400">
        <div className="w-8 h-8 border-2 border-amber-500 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
        <p className="text-xs font-mono">{t('eventDetail.loading')}</p>
      </div>
    );
  }

  if (error || !eventData) {
    return (
      <div className="max-w-2xl mx-auto py-16 text-center space-y-4">
        <h2 className="text-lg font-bold text-rose-400">{t('eventDetail.dossierUnavailable')}</h2>
        <p className="text-xs text-slate-400">{error || t('eventDetail.eventNotFound')}</p>
        <button
          onClick={() => navigate('/')}
          className="px-4 py-2 rounded-lg bg-slate-900 border border-slate-700 text-white text-xs font-semibold hover:bg-slate-800 transition cursor-pointer"
        >
          {t('eventDetail.backToFeed')}
        </button>
      </div>
    );
  }

  const bookmarked = isBookmarked(eventData._id);
  const primaryArticle = eventData.primaryArticleId;

  const lang = i18n.language || 'en';
  const locale = lang.startsWith('hi') ? 'hi-IN' : 'en-US';
  const formattedDate = eventData.createdAt
    ? new Date(eventData.createdAt).toLocaleDateString(locale, {
        dateStyle: 'medium',
        timeStyle: 'short',
      })
    : '';

  const eventTypeLabel = eventData.eventType
    ? t(`eventTypes.${eventData.eventType}`, { defaultValue: eventData.eventType.replace(/_/g, ' ') })
    : '';

  const localizedSummary = translateNewsText(eventData.summary, lang);
  const localizedArticleExcerpt = primaryArticle?.excerpt
    ? translateNewsText(primaryArticle.excerpt, lang)
    : '';
  const localizedArticleTitle = primaryArticle?.title
    ? translateNewsText(primaryArticle.title, lang)
    : '';

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Navigation & Action Bar */}
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <button
          onClick={() => navigate(-1)}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-800 bg-slate-900 text-slate-300 hover:text-white hover:bg-slate-800 text-xs font-semibold transition cursor-pointer"
        >
          <ArrowLeft size={14} />
          <span>{t('eventDetail.back')}</span>
        </button>

        <div className="flex items-center gap-2">
          {/* Export Briefing */}
          <button
            onClick={handleExportBriefing}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-800 bg-slate-900 text-slate-300 hover:text-white hover:bg-slate-800 text-xs font-semibold transition cursor-pointer"
            title={t('eventDetail.exportBriefing')}
          >
            <Download size={13} />
            <span>{t('eventDetail.exportBriefing')}</span>
          </button>

          {/* Share / Copy */}
          <button
            onClick={handleCopyLink}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-800 bg-slate-900 text-slate-300 hover:text-white hover:bg-slate-800 text-xs font-semibold transition cursor-pointer"
          >
            {copied ? (
              <>
                <Check size={13} className="text-emerald-400" />
                <span className="text-emerald-400">{t('eventDetail.copied')}</span>
              </>
            ) : (
              <>
                <Share2 size={13} />
                <span>{t('eventDetail.share')}</span>
              </>
            )}
          </button>

          {/* Bookmark */}
          {isAuthenticated && (
            <button
              onClick={() => toggleBookmark(eventData._id)}
              className={`inline-flex items-center gap-2 px-3.5 py-1.5 rounded-lg border text-xs font-semibold transition cursor-pointer ${
                bookmarked
                  ? 'bg-amber-500/20 border-amber-500/40 text-amber-400'
                  : 'bg-slate-900 border-slate-800 text-slate-300 hover:text-white'
              }`}
            >
              <Bookmark size={14} fill={bookmarked ? 'currentColor' : 'none'} />
              <span>{bookmarked ? t('eventDetail.saved') : t('eventDetail.saveDossier')}</span>
            </button>
          )}
        </div>
      </div>

      {/* Main Event Header Card */}
      <div
        className="p-6 sm:p-8 rounded-3xl border space-y-5 shadow-2xl"
        style={{
          backgroundColor: 'var(--color-surface-1)',
          borderColor: 'var(--color-border)',
        }}
      >
        <div className="flex items-center gap-2 flex-wrap">
          <SeverityBadge severity={eventData.severity} />
          <span className="text-xs font-mono font-bold uppercase tracking-wider text-amber-400 bg-amber-950/40 border border-amber-800/60 px-2.5 py-0.5 rounded">
            {eventTypeLabel}
          </span>
          <CredibilityBadge
            label={eventData.credibilityLabel}
            score={eventData.credibilityScore}
          />
        </div>

        <h1 className="text-2xl sm:text-3xl font-extrabold text-white leading-tight">
          {localizedSummary}
        </h1>

        <div className="flex items-center gap-4 text-xs text-slate-400 font-mono border-t border-slate-800/80 pt-4 flex-wrap">
          <span className="flex items-center gap-1.5">
            <Globe size={13} className="text-amber-400" />
            <span>{t('eventDetail.source')}: {primaryArticle?.sourceId?.name || 'News Wire'}</span>
          </span>
          <span>•</span>
          <span className="flex items-center gap-1.5">
            <Clock size={13} />
            <span>{formattedDate}</span>
          </span>
        </div>
      </div>

      {/* ARTICLE SUMMARY SECTION */}
      <div
        className="p-6 rounded-2xl border space-y-3"
        style={{
          backgroundColor: 'var(--color-surface-1)',
          borderColor: 'var(--color-border)',
        }}
      >
        <div className="flex items-center justify-between gap-2 flex-wrap pb-2 border-b border-slate-800/80">
          <div className="flex items-center gap-2">
            <Newspaper size={16} className="text-amber-400" />
            <h2 className="text-sm font-bold text-white uppercase tracking-wider font-mono">
              {t('eventDetail.articleSummary')}
            </h2>
            {primaryArticle?.sourceId?.name && (
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-900 text-slate-300 border border-slate-700">
                {primaryArticle.sourceId.name}
              </span>
            )}
          </div>

          {primaryArticle?.url && (
            <a
              href={primaryArticle.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-amber-400 hover:underline inline-flex items-center gap-1 font-medium transition-colors"
            >
              <span>{t('eventDetail.readOriginal')}</span>
              <ExternalLink size={13} />
            </a>
          )}
        </div>

        {localizedArticleExcerpt ? (
          <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
            {localizedArticleExcerpt}
          </p>
        ) : (
          <div className="text-xs text-slate-500 italic">
            {primaryArticle?.url ? (
              <a
                href={primaryArticle.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-amber-400/90 hover:text-amber-300 hover:underline inline-flex items-center gap-1 font-medium not-italic"
              >
                {t('eventDetail.summaryUnavailable')}
              </a>
            ) : (
              <span>{t('eventDetail.summaryUnavailable')}</span>
            )}
          </div>
        )}
      </div>

      {/* Section 1: Who Is Involved */}
      <div
        className="p-6 rounded-2xl border space-y-3"
        style={{
          backgroundColor: 'var(--color-surface-1)',
          borderColor: 'var(--color-border)',
        }}
      >
        <h2 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2">
          <MapPin size={16} className="text-amber-400" />
          {t('eventDetail.keyEntitiesGeography')}
        </h2>

        <div className="flex items-center gap-2 flex-wrap pt-1">
          {eventData.countries?.map((country) => (
            <span
              key={country}
              className="px-3 py-1 rounded-lg bg-slate-900 border border-slate-800 text-slate-200 text-xs font-medium flex items-center gap-1.5"
            >
              <Globe size={12} className="text-amber-500" />
              {country}
            </span>
          ))}

          {eventData.sectors?.map((sector) => (
            <span
              key={sector}
              className="px-3 py-1 rounded-lg bg-slate-900 border border-slate-800 text-slate-300 text-xs font-mono"
            >
              {t('eventDetail.sectorLabel', { sector })}
            </span>
          ))}

          {eventData.entities?.map((ent) => (
            <span
              key={ent}
              className="px-3 py-1 rounded-lg bg-slate-900/60 border border-slate-800/80 text-slate-400 text-xs"
            >
              {ent}
            </span>
          ))}
        </div>
      </div>

      {/* Section 2: Potential Impact Assessment */}
      <div className="space-y-4">
        <h2 className="text-base font-bold text-white flex items-center gap-2">
          <TrendingUp size={18} className="text-amber-400" />
          <span>{t('eventDetail.domainImpactEvaluation', { count: impacts.length })}</span>
        </h2>

        {impacts.length === 0 ? (
          <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/20 text-center text-xs text-slate-400">
            {t('eventDetail.noImpactRules')}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {impacts.map((imp) => {
              const domainLabel = t(`domains.${imp.domain}`, { defaultValue: imp.domain });
              const explanationText = imp.explanation || imp.ruleExplanation || '';
              const localizedImpExplanation = translateNewsText(explanationText, lang);
              return (
                <div
                  key={imp._id}
                  className="p-5 rounded-2xl border space-y-3"
                  style={{
                    backgroundColor: 'var(--color-surface-1)',
                    borderColor: 'var(--color-border)',
                  }}
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-mono font-bold text-amber-400 bg-amber-950/40 px-2.5 py-0.5 rounded border border-amber-900/60">
                      {domainLabel}
                    </span>
                    <DirectionBadge direction={imp.direction} size="sm" />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center justify-between text-xs text-slate-400 font-mono">
                      <span>{t('eventDetail.severityImpact')}:</span>
                      <span className="font-bold text-white">{t(`badges.severity.${imp.severity}`, { defaultValue: imp.severity })}</span>
                    </div>
                    <div className="flex items-center justify-between text-xs text-slate-400 font-mono">
                      <span>{t('eventDetail.confidenceScoreLabel')}:</span>
                      <span className="font-bold text-amber-400">
                        {Math.round(imp.confidenceScore * 100)}%
                      </span>
                    </div>
                  </div>

                  {localizedImpExplanation && (
                    <p className="text-xs text-slate-300 leading-relaxed border-t border-slate-800/80 pt-2.5">
                      {localizedImpExplanation}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Section 3: Verified Facts & Evidence */}
      <div
        className="p-6 rounded-2xl border space-y-4"
        style={{
          backgroundColor: 'var(--color-surface-1)',
          borderColor: 'var(--color-border)',
        }}
      >
        <h2 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2">
          <ShieldCheck size={16} className="text-amber-400" />
          {t('eventDetail.extractedFactualClaims')}
        </h2>

        {eventData.facts && eventData.facts.length > 0 && (
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-slate-400 font-mono uppercase">
              {t('eventDetail.confirmedFactualStatements')}
            </h3>
            <ul className="space-y-2">
              {translateNewsArray(eventData.facts, lang).map((fact, idx) => (
                <li
                  key={idx}
                  className="text-xs text-slate-200 bg-slate-900/60 p-3 rounded-xl border border-slate-800/80 flex items-start gap-2.5 leading-relaxed"
                >
                  <CheckCircle2 size={15} className="text-emerald-400 shrink-0 mt-0.5" />
                  <span>{fact}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {eventData.uncertainties && eventData.uncertainties.length > 0 && (
          <div className="space-y-2 pt-2">
            <h3 className="text-xs font-bold text-slate-400 font-mono uppercase">
              {t('eventDetail.keyUncertainties')}
            </h3>
            <ul className="space-y-2">
              {translateNewsArray(eventData.uncertainties, lang).map((unc, idx) => (
                <li
                  key={idx}
                  className="text-xs text-amber-300/90 bg-amber-950/20 p-3 rounded-xl border border-amber-900/40 flex items-start gap-2.5 leading-relaxed"
                >
                  <HelpCircle size={15} className="text-amber-400 shrink-0 mt-0.5" />
                  <span>{unc}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Section 4: Primary Article Reference */}
      {primaryArticle && (
        <div
          className="p-6 rounded-2xl border flex items-center justify-between gap-4"
          style={{
            backgroundColor: 'var(--color-surface-1)',
            borderColor: 'var(--color-border)',
          }}
        >
          <div className="space-y-1">
            <span className="text-[11px] font-mono text-slate-400 uppercase">
              {t('eventDetail.originalReport')}
            </span>
            <h3 className="text-sm font-bold text-white line-clamp-1">
              {localizedArticleTitle || primaryArticle.title}
            </h3>
          </div>

          <a
            href={primaryArticle.url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-amber-500 text-slate-950 font-bold text-xs hover:bg-amber-400 transition cursor-pointer shrink-0"
          >
            <span>{t('eventDetail.readOriginal')}</span>
            <ExternalLink size={13} />
          </a>
        </div>
      )}
    </div>
  );
}
