import React, { useState, useEffect, useCallback } from 'react';
import { ShieldCheck, Filter, ChevronLeft, ChevronRight, AlertCircle, TrendingDown, TrendingUp } from 'lucide-react';
import apiClient from '../lib/apiClient.js';
import DirectionBadge from '../components/common/DirectionBadge.jsx';
import SeverityBadge from '../components/common/SeverityBadge.jsx';

// ─── Impacts Page ─────────────────────────────────────────────────────────────
// Cross-domain qualitative impact assessments view.
// ─────────────────────────────────────────────────────────────────────────────

const DOMAINS = [
  'ALL',
  'ENERGY',
  'OIL_AND_GAS',
  'TRADE',
  'SUPPLY_CHAIN',
  'CURRENCY',
  'INFLATION',
  'DEFENSE',
  'TECHNOLOGY',
  'SEMICONDUCTORS',
  'FOOD_AGRICULTURE',
  'DIPLOMACY',
  'GLOBAL_STABILITY',
  'FINANCIAL_MARKETS',
];

const DIRECTIONS = ['ALL', 'NEGATIVE', 'RISK_INCREASE', 'POSITIVE', 'NEUTRAL'];

export default function ImpactsPage() {
  const [impacts, setImpacts] = useState([]);
  const [pagination, setPagination] = useState({ page: 1, limit: 15, total: 0, totalPages: 1 });
  const [selectedDomain, setSelectedDomain] = useState('ALL');
  const [selectedDirection, setSelectedDirection] = useState('ALL');
  const [page, setPage] = useState(1);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchImpacts = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);

      const params = { page, limit: 15 };
      if (selectedDomain !== 'ALL') params.domain = selectedDomain;
      if (selectedDirection !== 'ALL') params.direction = selectedDirection;

      const res = await apiClient.get('/impacts', { params });
      setImpacts(res.data || []);
      if (res.pagination) setPagination(res.pagination);
    } catch (err) {
      setError(err.message || 'Failed to fetch impact assessments');
    } finally {
      setIsLoading(false);
    }
  }, [page, selectedDomain, selectedDirection]);

  useEffect(() => {
    fetchImpacts();
  }, [fetchImpacts]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
          <ShieldCheck size={20} className="text-amber-400" />
          <span>Cross-Domain Impact Intelligence</span>
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Macroeconomic and sector-specific impact evaluations generated by deterministic reasoning rules
        </p>
      </div>

      {/* Filter Bar */}
      <div
        className="p-4 rounded-xl border flex flex-wrap items-center justify-between gap-3"
        style={{
          backgroundColor: 'var(--color-surface-1)',
          borderColor: 'var(--color-border)',
        }}
      >
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs font-semibold text-slate-400 flex items-center gap-1">
            <Filter size={12} />
            Domain:
          </span>
          <select
            value={selectedDomain}
            onChange={(e) => {
              setSelectedDomain(e.target.value);
              setPage(1);
            }}
            className="px-3 py-1.5 text-xs rounded-lg border bg-slate-950 text-slate-200 border-slate-700 focus:border-amber-500 focus:outline-none cursor-pointer"
          >
            {DOMAINS.map((d) => (
              <option key={d} value={d}>
                {d.replace(/_/g, ' ')}
              </option>
            ))}
          </select>

          <span className="text-xs font-semibold text-slate-400 ml-2">Direction:</span>
          <select
            value={selectedDirection}
            onChange={(e) => {
              setSelectedDirection(e.target.value);
              setPage(1);
            }}
            className="px-3 py-1.5 text-xs rounded-lg border bg-slate-950 text-slate-200 border-slate-700 focus:border-amber-500 focus:outline-none cursor-pointer"
          >
            {DIRECTIONS.map((dir) => (
              <option key={dir} value={dir}>
                {dir.replace(/_/g, ' ')}
              </option>
            ))}
          </select>
        </div>

        <div className="text-xs text-slate-400">
          Showing {impacts.length} of {pagination.total} assessments
        </div>
      </div>

      {/* List / Grid of Assessments */}
      {isLoading ? (
        <div className="py-20 flex flex-col items-center justify-center text-slate-400 space-y-3">
          <div className="w-8 h-8 border-2 border-amber-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-xs">Loading impact radar...</p>
        </div>
      ) : error ? (
        <div className="p-8 rounded-xl border border-rose-900/60 bg-rose-950/20 text-center text-rose-400">
          <AlertCircle size={32} className="mx-auto mb-2 text-rose-400" />
          <p className="text-xs">{error}</p>
        </div>
      ) : impacts.length === 0 ? (
        <div className="p-12 rounded-xl border border-slate-800 bg-slate-900/20 text-center text-slate-400 text-xs">
          No impact assessments found for the selected domain/direction.
        </div>
      ) : (
        <div className="space-y-3">
          {impacts.map((impact) => (
            <div
              key={impact._id}
              className="p-4 rounded-xl border transition hover:border-slate-700"
              style={{
                backgroundColor: 'var(--color-surface-1)',
                borderColor: 'var(--color-border)',
              }}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="text-xs font-mono font-bold text-amber-400 bg-amber-950/40 border border-amber-800/60 px-2 py-0.5 rounded">
                    {impact.domain}
                  </span>
                  <DirectionBadge direction={impact.direction} />
                  <SeverityBadge severity={impact.severity} size="sm" />
                </div>

                <div className="text-[11px] font-mono text-slate-400">
                  Confidence: <span className="text-emerald-400 font-bold">{Math.round(impact.confidenceScore * 100)}%</span>
                  <span className="mx-1.5 text-slate-600">|</span>
                  Rule: <span className="text-slate-300">{impact.ruleId}</span>
                </div>
              </div>

              <p className="text-xs text-slate-200 leading-relaxed font-medium">
                {impact.explanation}
              </p>

              {impact.eventId && (
                <div className="mt-3 pt-2 border-t border-slate-800/80 text-[11px] text-slate-400 flex items-center justify-between">
                  <div className="truncate mr-2">
                    <span className="text-slate-500">Related Event: </span>
                    <span className="text-slate-300">{impact.eventId.summary}</span>
                  </div>
                  <span className="shrink-0 font-mono text-slate-500">
                    {impact.eventId.eventType}
                  </span>
                </div>
              )}
            </div>
          ))}

          {/* Pagination */}
          {pagination.totalPages > 1 && (
            <div className="pt-4 flex items-center justify-between border-t border-slate-800">
              <button
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={!pagination.hasPrevPage}
                className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium border border-slate-700 bg-slate-900 text-slate-300 hover:text-white disabled:opacity-40 cursor-pointer"
              >
                <ChevronLeft size={13} />
                <span>Previous</span>
              </button>

              <span className="text-xs text-slate-400 font-mono">
                Page {pagination.page} of {pagination.totalPages}
              </span>

              <button
                onClick={() => setPage((p) => Math.min(pagination.totalPages, p + 1))}
                disabled={!pagination.hasNextPage}
                className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium border border-slate-700 bg-slate-900 text-slate-300 hover:text-white disabled:opacity-40 cursor-pointer"
              >
                <span>Next</span>
                <ChevronRight size={13} />
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
